export class Rptas {
  constructor(
    public rpt1: String,
    public rpt2: String,
    public rpt3: String,
    public rpt4: String,
    public rpt5: String,
    public rpt6: String,
    public rpt7: String,
    public rpt8: String,
    public rpt9: String,
    public rpt10: String,
    public rpt11: String,
    public rpt12: String,
    public rpt13: String,
    public rpt14: String,
    public rpt15: String,
    public rpt16: String,
    public rpt17: String,
    public rpt18: String,
    public rpt19: String,
    public rpt20: String,
    public rpt21: String,
    public rpt22: String,
    public rpt23: String,
    public rpt24: String,
    public rpt25: String,
    public rpt26: String,
    public rpt27: String,
    public rpt28: String,
    public rpt29: String,
    public rpt30: String,
    public rpt31: String,
    public rpt32: String,
    public rpt33: String,
    public rpt34: String,
    public rpt35: String,
    public rpt36: String,
    public rpt37: String,
    public test_id: number,
    ) {}
}
